=begin
        Gemfile > Contains all the necessary GEMS for this Project!

NOTE:
    All necessary info contained in README.md
=end
source "https://rubygems.org"

ruby "~> 3.0.0"

gem "sqlite3"
gem "sinatra"

# Web-Servers
gem "thin" # Will be used for our Project! 
gem "puma"