=begin
    Gemfile > Contains all the necessary GEMS for this Project !

NOTE:
    - Command:
        bundle install 
                    ==> To install all the necessary Gems
=end

source "https://rubygems.org"

gem "sqlite3"
gem "sinatra"

# Web-Servers
gem "thin" # Will be used for our Project! 
gem "puma"